service: dw-fullstack

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  stage: dev

functions:
  products:
    handler: src/handler.products
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin


plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000